### ISSUE TITLE
Cannot Compile

### ISSUE THREAD

**Issue by Baa14453** [andijakl/nfcinteractor#1]
Hello!
I know this is a discontinued project but i'm trying to compile with QtSDK I've set it to Symbian Anna and I'm on the right version.

When I try to build it gives me this - 

 FAILED compile  for arm.v5.urel.gcce4_4_1:  main.cpp
  mmp: nfcinteractor_exe.mmp
    mingw32-make[1]: **\* [C:/QTSdk/QT-SDK/Symbian/SDKs/Symbian3Qt474/epoc32/build/nfcinteractor-master/c_e2905167e1579238/nfcinteractor_exe/armv5/urel/main.o] Error 1
    mingw32-make[1]: **\* Waiting for unfinished jobs....
sbs: error: The make-engine exited with errors.
make.exe: Leaving directory `C:/QTSdk/nfcinteractor-master2/nfcinteractor-master'
make.exe: **\* [release-gcce] Error 1
17:16:00: The process "C:\QTSdk\QT-SDK\Symbian\SDKs\Symbian3Qt474\epoc32\tools\make.exe" exited with code 2.
Error while building project nfcinteractor (target: Symbian Device)
When executing build step 'Make'

Any ideas? :(

**Comment by Baa14453** [comment]
C:\QTSdk\nfcinteractor-master2\nfcinteractor-master\iap\iapmanager.h:22: error: iapclient.h: No such file or directory

There is also this.

**Comment by kayschubert1** [comment]
You should take the Belle SDK and GCCE 4.6.3 or the ARM Compiler

**Comment by andijakl** [comment]
The IAP (In App Purchasing) was a plug-in to the SDK.
If you compile the app for yourself, you should compile the full / unlimited version without IAP enabled.

Uncomment the UNLIMITED_VERSION in the nfcinteractor.pro file in line 5 to switch to the full version and disable IAP:
https://github.com/andijakl/nfcinteractor/blob/master/nfcinteractor.pro

**Comment by kayschubert1** [comment]
Thank you very much for the explanation.

Would you please compile and provide for download such a version without IAP?

That would be great. Thank you.

**Comment by Baa14453** [comment]
ok, I've finally done it. I had to uncomment line 5 of the .pro
I then had to comment out line 14

I also had to re-enable the com port 3 which I had disabled to make Nokia Suite work in Windows 10

Then I had to install the CODA application. After doing all this it created the .sis file and installed onto the device fine!

Thanks for your help guys :dancer: 

I have attached the final .sis file.
[nfcinteractor.zip](https://github.com/andijakl/nfcinteractor/files/186843/nfcinteractor.zip)

**Comment by kayschubert1** [comment]
@Hugo14453 : Thank you very much.

Unfortunately the zip can not be opened on a Symbian device: corrupt zip

Would you please provide a new zip or the sis?

Which development environment you have used? (SDK, compiler)

@andijakl : is a self-signed certificate sufficient to fully use the app or needs it capabilities, that go beyond self-signed?

Is it ok to compile it for Anna or needs it Belle?

**Comment by Baa14453** [comment]
Sorry, the .sis file is contained with the .zip GitHub only let's me upload specific file formats.
Extract the zip file and the .sis should be inside.

I used QT Creator (So SDK I think) and I just clicked the Run button.

**Comment by Baa14453** [comment]
Sorry, I hadn't realised the .zip was corrupt.
Try this one 
[nfcinteractor.zip](https://github.com/andijakl/nfcinteractor/files/188373/nfcinteractor.zip)

**Comment by andijakl** [comment]
A self-sign certificate is sufficient without any in-app purchasing enabled. In general, the Symbian phones should run Belle, as Anna was a lot more limited with regards to NFC functionality (and also had some more issues). However, as far as I remember, for compiling it shouldn't matter. Just make sure you're using the latest available Qt Mobility version!

**Comment by kayschubert1** [comment]
Thank you very much to both of you for the working zip and the comprehensive developer information.

The background for my questions is the following: I would like to upload this unlimited version to the Symbian AppList app store. So it should work on as many platforms (Symbian^3, Anna, Belle) as possible without any restrictions and on Stock Firmware (self-signed certificate).

My last wish now: would someone please compile a version for Symbian Anna (with latest Qt Mobility), with the version number increased to 4.3 (in the app "4.3.0", but also in the sis installer "4.30(0)", this is important for automatic update recognition in AppList) and with the self-signed certificate app UID in the following range: 0xA0000000 … 0xAFFFFFFF (this is important for installing on Stock Firmware)

**Comment by Baa14453** [comment]
Going to be honest i'm a complete amateur at this, but I think i've got it right on this one.
[nfcinteractor.zip](https://github.com/andijakl/nfcinteractor/files/190503/nfcinteractor.zip)
